// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qicanpsrzzqbpzdxkgwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpY2FucHNyenpxYnB6ZHhrZ3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjg1MzQsImV4cCI6MjA3MzcwNDUzNH0.t-Sgp2GF2xO0r8Y5xkoUZIgtkpBLj_vOlAp4KnZxoBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});